### ISSUE TITLE
Add question to the readme list.

### ISSUE THREAD

**Issue by anurag629** [anurag629/LeetCode-Solution#5]
# :1st_place_medal: Want to contribute. You are welcome here :100: 

# For this you have to do the following things :
- ## Search question whose solution is provided [ here ](https://github.com/anurag629/LeetCode-Solution) but not listed in [ Readme File. ](https://github.com/anurag629/LeetCode-Solution/blob/main/README.md)

### Remaining :
- [ ] 217 

### Completed :

- [x] 1920 @rzkyadhi 
- [x] 1929 @rzkyadhi
- [X] 876 @shvmngi 
- [x] 2011 @shvmngi 
- [x] 19 @shvmngi 
- [x] 4 @shvmngi 
- [x] 3 @shvmngi 
- [x] 8 @shvmngi 
- [x] 10 @shvmngi 
- [x] 21 @shvmngi 
- [x] 26 @shvmngi 
- [x] 7 @shvmngi 

## If you find the Question then ask @anurag629 to assign you that question.

<code>Note ::: You have to add question in the list according to question number.</code>

**Comment by rzkyadhi** [comment]
Hello this is my first time to contribute an issue in github. I already found some question that not listed in Readme File. Can you assign me to this issue? Thank you :)

**Comment by anurag629** [comment]
> Hello this is my first time to contribute an issue in github. I already found some question that not listed in Readme File. Can you assign me to this issue? Thank you :)

Reply with the question number which are not on the list then I will assign those to you.

**Comment by rzkyadhi** [comment]
Question number 1920 and 1929

**Comment by anurag629** [comment]
> Question number 1920 and 1929

Done!
Now, Go ahead and make a PR

**Comment by anurag629** [comment]
@rzkyadhi  if you have any doubt ask here...
